### ISSUE TITLE
Unit tests 

### ISSUE THREAD

**Issue by p-mitana** [d-utils/validation#2]
Unit tests don't compile with the newer DMD versions due to implicit conversion from Nullable to underlying type, which has been removed.

I have filed a PR for this some days ago – I would be greatful for including it and releasing and tagging a new version, so that me and other people willing to use dutils (especially for rabbitmq) won'e need to have their forks just for this fix. Thank you in advance!

#1

**Comment by tirithen** [comment]
@p-mitana thanks for the reminder, your fix has been released.
